title: Oni - A Linux Lover
description: My Personal Blog
author: Oni Ranger
logo: images/avatar.jpeg
github: https://github.com/ita93
about: Linux Lover

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: Phi Nguyen Dinh
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
